# Generated by Django 4.2.11 on 2024-05-01 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0002_rename_score_rating_rating_alter_rating_movie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actors",
            unique_together={("name", "surname")},
        ),
        migrations.AlterUniqueTogether(
            name="directors",
            unique_together={("name", "surname")},
        ),
    ]
