# Generated by Django 4.2.11 on 2024-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0003_alter_actors_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="poster",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="posters/"
            ),
        ),
    ]
