# Generated by Django 4.2.11 on 2024-05-03 11:41

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("BackEnd", "0004_movies_poster"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actors",
            options={
                "ordering": ("name",),
                "verbose_name": "actor",
                "verbose_name_plural": "actors",
            },
        ),
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="directors",
            options={
                "ordering": ("name",),
                "verbose_name": "director",
                "verbose_name_plural": "directors",
            },
        ),
        migrations.AlterModelOptions(
            name="movies",
            options={
                "ordering": ("title",),
                "verbose_name": "movie",
                "verbose_name_plural": "movies",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={
                "ordering": ("id",),
                "verbose_name": "rating",
                "verbose_name_plural": "ratings",
            },
        ),
        migrations.RemoveField(
            model_name="platformusers",
            name="name",
        ),
        migrations.RemoveField(
            model_name="platformusers",
            name="surname",
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z ]+$")],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[django.core.validators.RegexValidator("^[a-zA-Z ]+$")],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
