# Generated by Django 4.2.11 on 2024-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Filmaffinity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
