# Generated by Django 4.2.11 on 2024-05-14 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Filmaffinity", "0002_alter_rating_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformusers",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s]+$",
                        message="Enter a valid first name.",
                    )
                ],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="platformusers",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s]+$",
                        message="Enter a valid last name.",
                    )
                ],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
