name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Cambiar al directorio Backend
        run: cd Backend
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
      - name: Ejecutar pruebas
        run: |
          cd Backend
          python manage.py test
